from pathlib import Path
path = Path('1stand/src/app/components/payment/payment.component.ts')
text = path.read_text(encoding='latin-1')
old_block = "  loadMedicalAttentionByAppointment(appointmentId: number, options: { forceAmount?: boolean } = {}): void {\n    if (!appointmentId) {\n      console.warn('No se seleccion�� una cita v��lida.');\n      this.applyAttentionData(null);\n      return;\n    }\n\n    this.loadMedicalAttentionByAppointment(Number(appointmentId));\n  }\n\n  exportToPDF() {"
if old_block not in text:
    raise SystemExit('loadMedicalAttentionByAppointment block not found')
new_block = "  loadMedicalAttentionByAppointment(appointmentId: number, options: { forceAmount?: boolean } = {}): void {\n    if (!appointmentId) {\n      console.warn('No se seleccionó una cita válida.');\n      this.applyAttentionData(null, options);\n      return;\n    }\n\n    this.medicalAttentionService.getMedicalAttentionByAppointment(appointmentId).subscribe({\n      next: (attention: any) => {\n        console.log('Atención médica recibida:', attention);\n        this.applyAttentionData(attention, options);\n      },\n      error: (err: any) => {\n        console.error('Error al cargar la atención médica:', err);\n        this.applyAttentionData(null, options);\n      }\n    });\n  }\n\n  private applyAttentionData(attention: any | null, options: { forceAmount?: boolean } = {}): void {\n    const { forceAmount = true } = options;\n\n    if (attention) {\n      this.attentionTreatments = Array.isArray(attention.treatments) ? attention.treatments : [];\n      this.otherTreatments = Array.isArray(attention.other_treatments) ? attention.other_treatments : [];\n      const total = Number(attention.total_cost ?? 0);\n      this.selectedAttentionTotal = total;\n\n      const firstTreatmentId = this.attentionTreatments.length === 1 ? (this.attentionTreatments[0].id ?? '') : '';\n      const patch: any = { treatment_id: firstTreatmentId };\n      if (forceAmount) {\n        patch.amount = total;\n      }\n\n      this.paymentForm.patchValue(patch, { emitEvent: false });\n    } else {\n      this.attentionTreatments = [];\n      this.otherTreatments = [];\n      this.selectedAttentionTotal = null;\n      const patch: any = { treatment_id: '' };\n      if (forceAmount) {\n        patch.amount = '';\n      }\n      this.paymentForm.patchValue(patch, { emitEvent: false });\n    }\n  }\n\n  private isAttendedAppointment(appointment: any): boolean {\n    if (!appointment) {\n      return false;\n    }\n    const status = (appointment.status ?? appointment.appointment_status ?? '').toString().toLowerCase();\n    return status === 'attended';\n  }\n\n  exportToPDF() {"
text = text.replace(old_block, new_block, 1)
path.write_text(text, encoding='latin-1')
