from pathlib import Path
path = Path('1stand/src/app/components/payment/payment.component.ts')
text = path.read_text(encoding='latin-1')
old = "  loadMedicalAttentionByAppointment(appointmentId: number, options: { forceAmount?: boolean } = {}): void {\r\n    if (!appointmentId) {\r\n      console.warn('No se seleccion�� una cita vǭlida.');\r\n      this.applyAttentionData(null);\r\n      return;\r\n    }\r\n\r\n    this.loadMedicalAttentionByAppointment(Number(appointmentId));\r\n  }\r\n\r\n  exportToPDF() {"
if old not in text:
    raise SystemExit('Old loadMedicalAttentionByAppointment block not found')
new = "  loadMedicalAttentionByAppointment(appointmentId: number, options: { forceAmount?: boolean } = {}): void {\r\n    if (!appointmentId) {\r\n      console.warn('No se seleccionó una cita válida.');\r\n      this.applyAttentionData(null, options);\r\n      return;\r\n    }\r\n\r\n    this.medicalAttentionService.getMedicalAttentionByAppointment(appointmentId).subscribe({\r\n      next: (attention: any) => {\r\n        console.log('Atención médica recibida:', attention);\r\n        this.applyAttentionData(attention, options);\r\n      },\r\n      error: (err: any) => {\r\n        console.error('Error al cargar la atención médica:', err);\r\n        this.applyAttentionData(null, options);\r\n      }\r\n    });\r\n  }\r\n\r\n  private applyAttentionData(attention: any | null, options: { forceAmount?: boolean } = {}): void {\r\n    const { forceAmount = true } = options;\r\n\r\n    if (attention) {\r\n      this.attentionTreatments = Array.isArray(attention.treatments) ? attention.treatments : [];\r\n      this.otherTreatments = Array.isArray(attention.other_treatments) ? attention.other_treatments : [];\r\n      const total = Number(attention.total_cost ?? 0);\r\n      this.selectedAttentionTotal = total;\r\n\r\n      const firstTreatmentId = this.attentionTreatments.length === 1 ? (this.attentionTreatments[0].id ?? '') : '';\r\n      const patch: any = { treatment_id: firstTreatmentId };\r\n      if (forceAmount) {\r\n        patch.amount = total;\r\n      }\r\n\r\n      this.paymentForm.patchValue(patch, { emitEvent: false });\r\n    } else {\r\n      this.attentionTreatments = [];\r\n      this.otherTreatments = [];\r\n      this.selectedAttentionTotal = null;\r\n      const patch: any = { treatment_id: '' };\r\n      if (forceAmount) {\r\n        patch.amount = '';\r\n      }\r\n      this.paymentForm.patchValue(patch, { emitEvent: false });\r\n    }\r\n  }\r\n\r\n  private isAttendedAppointment(appointment: any): boolean {\r\n    if (!appointment) {\r\n      return false;\r\n    }\r\n    const status = (appointment.status ?? appointment.appointment_status ?? '').toString().toLowerCase();\r\n    return status === 'attended';\r\n  }\r\n\r\n  exportToPDF() {"
text = text.replace(old, new, 1)
path.write_text(text, encoding='latin-1')
