# -*- coding: latin-1 -*-
from pathlib import Path
path = Path('1stand/src/app/components/payment/payment.component.html')
text = path.read_text(encoding='latin-1')
old = "      <div>\r\n        <label for=\"treatment_id\">Tratamiento</label>\r\n        <select id=\"treatment_id\" formControlName=\"treatment_id\" class=\"form-control\">\r\n          <option value=\"\">Seleccione un tratamiento</option>\r\n          <option *ngFor=\"let treatment of treatments\" [value]=\"treatment.id\">\r\n            {{ treatment.nombre }}\r\n          </option>\r\n        </select>\r\n      </div>\r\n\r\n      <div *ngIf=\"attentionTreatments.length\" class=\"mt-3\">\r\n        <h5>Tratamientos de la atenciÃ³n</h5>\r\n        <ul>\r\n          <li *ngFor=\"let treatment of attentionTreatments\">\r\n            {{ treatment.nombre }} - {{ (treatment.precio || treatment.price) | currency:'USD' }}\r\n          </li>\r\n        </ul>\r\n      </div>\r\n\r\n      <div *ngIf=\"otherTreatments && otherTreatments.length > 0\" class=\"mt-3\">\r\n        <h5>Otros Tratamientos</h5>\r\n        <ul>\r\n          <li *ngFor=\"let ot of otherTreatments\">\r\n            {{ ot.name }} - {{ ot.price | currency:'USD' }}\r\n          </li>\r\n        </ul>\r\n      </div>\r\n\r\n      <div class=\"mt-3\" *ngIf=\"selectedAttentionTotal !== null\">\r\n        <h5>Costo total de la atenciÃ³n</h5>\r\n        <p>{{ selectedAttentionTotal | currency:'USD' }}</p>\r\n      </div>\r\n"
if old not in text:
    raise SystemExit('select block not found')
new = "      <div class=\"mt-3\">\r\n        <label for=\"treatment_id\" class=\"form-label\">Tratamientos</label>\r\n        <select\r\n          id=\"treatment_id\"\r\n          formControlName=\"treatment_id\"\r\n          class=\"form-select\"\r\n          [disabled]=\"true\">\r\n          <option *ngIf=\"!attentionTreatments.length\" value=\"\">Selecciona una cita atendida</option>\r\n          <option *ngFor=\"let treatment of attentionTreatments\" [value]=\"treatment.id\">\r\n            {{ treatment.nombre }} - {{ (treatment.precio || treatment.price) | currency:'USD' }}\r\n          </option>\r\n        </select>\r\n        <small class=\"form-text text-muted\">Los tratamientos se cargan automÃ¡ticamente desde la atención médica.</small>\r\n      </div>\r\n\r\n      <div *ngIf=\"attentionTreatments.length\" class=\"mt-3\">\r\n        <h5>Detalle de Tratamientos</h5>\r\n        <ul class=\"list-group\">\r\n          <li\r\n            class=\"list-group-item d-flex justify-content-between align-items-center\"\r\n            *ngFor=\"let treatment of attentionTreatments\">\r\n            <span>{{ treatment.nombre }}</span>\r\n            <span class=\"fw-semibold\">{{ (treatment.precio || treatment.price) | currency:'USD' }}</span>\r\n          </li>\r\n        </ul>\r\n      </div>\r\n\r\n      <div *ngIf=\"otherTreatments && otherTreatments.length\" class=\"mt-3\">\r\n        <h5>Otros Tratamientos</h5>\r\n        <ul class=\"list-group\">\r\n          <li\r\n            class=\"list-group-item d-flex justify-content-between align-items-center\"\r\n            *ngFor=\"let ot of otherTreatments\">\r\n            <span>{{ ot.name }}</span>\r\n            <span class=\"fw-semibold\">{{ ot.price | currency:'USD' }}</span>\r\n          </li>\r\n        </ul>\r\n      </div>\r\n\r\n      <div class=\"alert alert-info mt-3\" *ngIf=\"selectedAttentionTotal !== null\">\r\n        <strong>Total de la atención:</strong> {{ selectedAttentionTotal | currency:'USD' }}\r\n      </div>\r\n"
text = text.replace(old, new, 1)
path.write_text(text, encoding='latin-1')
